let pokemonList = [
  {
    id: 1,
    name: "Bulbasaur",
    type: "Grass/Poison",
    height: "0.7 m",
    weight: "6.9 kg",
  },
  {
    id: 2,
    name: "Ivysaur",
    type: "Grass/Poison",
    height: "1.0 m",
    weight: "13.0 kg",
  },
  {
    id: 3,
    name: "Venusaur",
    type: "Grass/Poison",
    height: "2.0 m",
    weight: "100.0 kg",
  },
  {
    id: 4,
    name: "Charmander",
    type: "Fire",
    height: "0.6 m",
    weight: "8.5 kg",
  },
  {
    id: 5,
    name: "Charmeleon",
    type: "Fire",
    height: "1.1 m",
    weight: "19.0 kg",
  },
  {
    id: 6,
    name: "Charizard",
    type: "Fire/Flying",
    height: "1.7 m",
    weight: "90.5 kg",
  },
  { id: 7, name: "Squirtle", type: "Water", height: "0.5 m", weight: "9.0 kg" },
  {
    id: 8,
    name: "Wartortle",
    type: "Water",
    height: "1.0 m",
    weight: "22.5 kg",
  },
  {
    id: 9,
    name: "Blastoise",
    type: "Water",
    height: "1.6 m",
    weight: "85.5 kg",
  },
];
